"""Generate ``<output_dir>/.env.example`` from config surfaces (BEAN-052).

Aggregates the environment-variable references discovered by
``analyze_config`` into a single ``.env.example`` file with one line per
variable. A developer recreating the project can use this as the
skeleton for their own ``.env`` — without having to crawl every config
bean to assemble the list manually.
"""

from __future__ import annotations

from pathlib import Path

from repo_mirror_kit.harvester.analyzers.surfaces import (
    ConfigSurface,
    SurfaceCollection,
)


def generate_env_example(
    surfaces: SurfaceCollection,
    output_dir: Path,
) -> Path:
    """Write ``<output_dir>/.env.example`` and return its path.

    Walks ``surfaces.config``, deduplicates env vars by name, sorts the
    result alphabetically (deterministic output across runs), and emits
    a comment + ``KEY=PLACEHOLDER`` line for each.

    The placeholder is chosen by name heuristic — never by the value
    inferred from source code, so the file does not leak real defaults
    or appear pre-populated with usable secrets.
    """
    by_name: dict[str, ConfigSurface] = {}
    for surface in surfaces.config:
        name = (surface.env_var_name or surface.name or "").strip()
        if not name:
            continue
        # First occurrence wins for description/usage; subsequent dupes
        # are dropped (deterministic since the SurfaceCollection lists are
        # already in detection order).
        by_name.setdefault(name, surface)

    lines: list[str] = [
        "# Generated by RepoMirrorKit harvester (BEAN-052).",
        "# One entry per environment variable referenced in the source.",
        "# Placeholders are heuristic — never copies of source defaults.",
        "# Replace each PLACEHOLDER with a real value before running.",
        "",
    ]

    for name in sorted(by_name):
        surface = by_name[name]
        lines.extend(_render_entry(name, surface))
        lines.append("")

    path = output_dir / ".env.example"
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return path


def _render_entry(name: str, surface: ConfigSurface) -> list[str]:
    """Render the comment + KEY=PLACEHOLDER lines for a single env var."""
    description = _describe(surface)
    placeholder = _placeholder_for(name)
    return [
        f"# {description}",
        f"{name}={placeholder}",
    ]


def _describe(surface: ConfigSurface) -> str:
    """Pick the most useful one-line description for a config surface."""
    enrichment = surface.enrichment or {}
    inferred = enrichment.get("inferred_intent") or enrichment.get(
        "behavioral_description"
    )
    if isinstance(inferred, str) and inferred.strip():
        return inferred.strip().splitlines()[0]
    if surface.usage_locations:
        sample = ", ".join(surface.usage_locations[:3])
        if len(surface.usage_locations) > 3:
            sample += f" (+{len(surface.usage_locations) - 3} more)"
        return f"Used in: {sample}"
    if surface.source_refs:
        sample = ", ".join(ref.file_path for ref in surface.source_refs[:3])
        return f"Referenced in: {sample}"
    return "Source location unknown"


def _placeholder_for(name: str) -> str:
    """Heuristic placeholder by env var name suffix.

    Rules (first match wins, case-insensitive):
        *_URL, *_URI, *_ENDPOINT, *_HOST, *_HOSTNAME → https://example.com
        *_PORT                                       → 8080
        *_TOKEN, *_KEY, *_SECRET, *_PASSWORD,
        *_PASSWD, *_API_KEY, *_PRIVATE_KEY           → your-secret-here
        DEBUG, *_DEBUG, *_VERBOSE                    → false
        *_TIMEOUT, *_INTERVAL                        → 30
        otherwise                                    → changeme
    """
    upper = name.upper()
    if any(
        upper.endswith(s)
        for s in ("_URL", "_URI", "_ENDPOINT", "_HOST", "_HOSTNAME")
    ):
        return "https://example.com"
    if upper.endswith("_PORT"):
        return "8080"
    if any(
        upper.endswith(s) or s in upper
        for s in (
            "_TOKEN",
            "_KEY",
            "_SECRET",
            "_PASSWORD",
            "_PASSWD",
            "_API_KEY",
            "_PRIVATE_KEY",
        )
    ):
        return "your-secret-here"
    if upper == "DEBUG" or upper.endswith(("_DEBUG", "_VERBOSE")):
        return "false"
    if upper.endswith(("_TIMEOUT", "_INTERVAL")):
        return "30"
    return "changeme"
