"""Generate ``<output_dir>/RUNBOOK.md`` from build/deploy surfaces (BEAN-053).

Aggregates the build, CI/CD, container, and IaC artifacts discovered by
``analyze_build_deploy`` into a single operational guide. Each section
lists the detected tools, their config files, and the named stages/targets
they expose. A developer recreating the project uses this as a checklist
of what scripts/jobs the recreated project must support.
"""

from __future__ import annotations

from pathlib import Path

from repo_mirror_kit.harvester.analyzers.surfaces import (
    BuildDeploySurface,
    SurfaceCollection,
)

# Top-level grouping by config_type. Order matters — install/build flow first,
# then CI, then containers/IaC, then platform.
_GROUPS: tuple[tuple[str, str, str], ...] = (
    ("Build Tools", "build_tool", "Make/just/task/etc. — local automation."),
    ("CI / CD", "ci_cd", "Continuous integration and delivery pipelines."),
    ("Containers", "container", "Docker, Compose, container-related config."),
    ("Infrastructure as Code", "iac", "Terraform, CloudFormation, Ansible, etc."),
    ("Platform / Deploy Targets", "platform", "Heroku, Vercel, Netlify, Fly, etc."),
)

# Operation categories surfaced as a quick-reference matrix at the top of the
# document. The harvester does not extract individual command strings, so each
# row points the reader at the config file(s) where the command is defined.
_OPERATIONS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("Install", ("install", "setup", "deps", "init", "bootstrap")),
    ("Dev / Run", ("dev", "start", "run", "serve", "watch")),
    ("Test", ("test", "spec", "pytest", "jest", "vitest", "check")),
    ("Lint / Format", ("lint", "format", "fmt", "style")),
    ("Build", ("build", "compile", "package", "dist", "bundle")),
    ("Deploy / Release", ("deploy", "publish", "release", "ship")),
)


def generate_runbook_md(
    surfaces: SurfaceCollection,
    output_dir: Path,
) -> Path:
    """Write ``<output_dir>/RUNBOOK.md`` and return its path."""
    text = _render(list(surfaces.build_deploy))
    path = output_dir / "RUNBOOK.md"
    path.write_text(text, encoding="utf-8")
    return path


def _render(items: list[BuildDeploySurface]) -> str:
    parts: list[str] = []
    parts.append(_render_header(items))
    parts.append(_render_operations_matrix(items))
    parts.append("## Detected Build/Deploy Surfaces\n")
    for title, config_type, blurb in _GROUPS:
        parts.append(_render_group(title, config_type, blurb, items))
    parts.append(_render_footer())
    return "\n".join(parts)


def _render_header(items: list[BuildDeploySurface]) -> str:
    return (
        "# RUNBOOK — Operational Guide\n"
        "\n"
        "Generated by RepoMirrorKit harvester (BEAN-053). Lists the build,\n"
        "CI, container, and infrastructure surfaces detected in the source\n"
        "repository. Use it as a checklist: a recreated version of this\n"
        "project should provide the same operations (install, run, test,\n"
        "lint, build, deploy) via equivalent tooling.\n"
        "\n"
        f"**Total build/deploy surfaces detected:** {len(items)}\n"
    )


def _render_operations_matrix(items: list[BuildDeploySurface]) -> str:
    """For each canonical operation (Install/Dev/Test/Lint/Build/Deploy),
    list the detected stages or targets that match the operation's
    keywords, with a citation back to the source file."""
    lines = ["## Operations Quick Reference", ""]
    lines.append("| Operation | Detected stages / targets | Source |")
    lines.append("|-----------|---------------------------|--------|")

    for op_name, keywords in _OPERATIONS:
        matches = _match_operation(items, keywords)
        if matches:
            for stage_or_target, source_path in matches:
                lines.append(
                    f"| {op_name} | `{stage_or_target}` | `{source_path}` |"
                )
        else:
            lines.append(
                f"| {op_name} | _(none detected — recreated project should still provide one)_ | — |"
            )
    lines.append("")
    return "\n".join(lines) + "\n"


def _match_operation(
    items: list[BuildDeploySurface],
    keywords: tuple[str, ...],
) -> list[tuple[str, str]]:
    """Return (stage_or_target, source_path) pairs matching any keyword."""
    matches: list[tuple[str, str]] = []
    seen: set[tuple[str, str]] = set()
    for surface in items:
        source_path = surface.name or "—"
        for label in [*surface.stages, *surface.targets]:
            lower = label.lower()
            if any(kw in lower for kw in keywords):
                key = (label, source_path)
                if key not in seen:
                    seen.add(key)
                    matches.append(key)
    return matches


def _render_group(
    title: str,
    config_type: str,
    blurb: str,
    items: list[BuildDeploySurface],
) -> str:
    """Render one config_type group section."""
    matched = [s for s in items if s.config_type == config_type]
    lines = [f"### {title} ({len(matched)})", "", f"_{blurb}_", ""]

    if not matched:
        lines.append("_(none detected)_\n")
        return "\n".join(lines) + "\n"

    lines.append("| Tool | Config file | Stages / Targets |")
    lines.append("|------|-------------|------------------|")
    for surface in matched:
        labels = [*surface.stages, *surface.targets]
        labels_str = ", ".join(f"`{label}`" for label in labels) if labels else "—"
        path = surface.name or "—"
        tool = surface.tool or "—"
        lines.append(f"| {tool} | `{path}` | {labels_str} |")
    lines.append("")
    return "\n".join(lines) + "\n"


def _render_footer() -> str:
    return (
        "## Notes\n"
        "\n"
        "- The harvester records config-file artifacts, not the literal\n"
        "  shell commands they invoke. To get an exact command, open the\n"
        "  cited config file or its corresponding bean under `beans/`.\n"
        "- Empty rows in the Operations table flag gaps the recreator\n"
        "  should still address (every project needs install/test/build,\n"
        "  even if the original lacks an explicit script).\n"
    )
