"""Tests for the .env.example generator (BEAN-052)."""

from __future__ import annotations

from pathlib import Path

from repo_mirror_kit.harvester.analyzers.surfaces import (
    ConfigSurface,
    SourceRef,
    SurfaceCollection,
)
from repo_mirror_kit.harvester.generator.env_example import (
    _placeholder_for,
    generate_env_example,
)


class TestPlaceholderHeuristics:
    """Per-name placeholder rules. First match wins."""

    def test_url_family(self) -> None:
        for name in (
            "DATABASE_URL",
            "REDIS_URI",
            "WEBHOOK_ENDPOINT",
            "DB_HOST",
            "PRIMARY_HOSTNAME",
        ):
            assert _placeholder_for(name) == "https://example.com", name

    def test_port_family(self) -> None:
        assert _placeholder_for("APP_PORT") == "8080"
        assert _placeholder_for("METRICS_PORT") == "8080"

    def test_secret_family(self) -> None:
        for name in (
            "JWT_SECRET",
            "API_KEY",
            "STRIPE_TOKEN",
            "DB_PASSWORD",
            "MYSQL_PASSWD",
            "ANTHROPIC_API_KEY",
            "SSH_PRIVATE_KEY",
        ):
            assert _placeholder_for(name) == "your-secret-here", name

    def test_debug_and_verbose(self) -> None:
        assert _placeholder_for("DEBUG") == "false"
        assert _placeholder_for("APP_DEBUG") == "false"
        assert _placeholder_for("LOG_VERBOSE") == "false"

    def test_timeout_interval(self) -> None:
        assert _placeholder_for("REQUEST_TIMEOUT") == "30"
        assert _placeholder_for("POLL_INTERVAL") == "30"

    def test_fallback(self) -> None:
        assert _placeholder_for("MYSTERY_VAR") == "changeme"
        assert _placeholder_for("APP_NAME") == "changeme"


class TestGenerateEnvExample:
    def _surfaces_with_vars(self, *names: str) -> SurfaceCollection:
        return SurfaceCollection(
            config=[
                ConfigSurface(
                    name=n,
                    env_var_name=n,
                    source_refs=[SourceRef(file_path=f"src/{n.lower()}.py")],
                    usage_locations=[f"src/{n.lower()}.py"],
                )
                for n in names
            ],
        )

    def test_writes_file_to_top_level(self, tmp_path: Path) -> None:
        path = generate_env_example(
            self._surfaces_with_vars("DATABASE_URL"), tmp_path
        )
        assert path == tmp_path / ".env.example"
        assert path.is_file()

    def test_empty_collection_writes_header_only(self, tmp_path: Path) -> None:
        path = generate_env_example(SurfaceCollection(), tmp_path)
        text = path.read_text()
        # Header preserved even when no vars detected.
        assert "Generated by RepoMirrorKit" in text

    def test_dedupes_by_var_name(self, tmp_path: Path) -> None:
        surfaces = SurfaceCollection(
            config=[
                ConfigSurface(name="X", env_var_name="DATABASE_URL"),
                ConfigSurface(name="Y", env_var_name="DATABASE_URL"),
                ConfigSurface(name="Z", env_var_name="DATABASE_URL"),
            ]
        )
        text = generate_env_example(surfaces, tmp_path).read_text()
        # Exactly one DATABASE_URL= line.
        assert text.count("DATABASE_URL=") == 1

    def test_alphabetical_order(self, tmp_path: Path) -> None:
        text = generate_env_example(
            self._surfaces_with_vars("ZEBRA", "ALPHA", "MEDIUM"), tmp_path
        ).read_text()
        # Alphabetically sorted: ALPHA before MEDIUM before ZEBRA
        assert text.index("ALPHA=") < text.index("MEDIUM=") < text.index("ZEBRA=")

    def test_each_var_has_comment(self, tmp_path: Path) -> None:
        text = generate_env_example(
            self._surfaces_with_vars("DATABASE_URL"), tmp_path
        ).read_text()
        # Comment line precedes the KEY=VALUE.
        idx = text.index("DATABASE_URL=")
        before = text[:idx]
        # Last non-empty line before the assignment must be a comment.
        last_line = [ln for ln in before.splitlines() if ln.strip()][-1]
        assert last_line.startswith("#")

    def test_placeholders_applied(self, tmp_path: Path) -> None:
        text = generate_env_example(
            self._surfaces_with_vars(
                "DATABASE_URL", "JWT_SECRET", "APP_PORT", "DEBUG", "MYSTERY"
            ),
            tmp_path,
        ).read_text()
        assert "DATABASE_URL=https://example.com" in text
        assert "JWT_SECRET=your-secret-here" in text
        assert "APP_PORT=8080" in text
        assert "DEBUG=false" in text
        assert "MYSTERY=changeme" in text

    def test_skips_surfaces_without_var_name(self, tmp_path: Path) -> None:
        surfaces = SurfaceCollection(
            config=[
                ConfigSurface(name="", env_var_name=""),
                ConfigSurface(name="GOOD", env_var_name="GOOD"),
            ]
        )
        text = generate_env_example(surfaces, tmp_path).read_text()
        assert "GOOD=" in text
        # Only one var line — empty surface skipped.
        assert text.count("=") == 1

    def test_uses_enrichment_intent_when_present(self, tmp_path: Path) -> None:
        surfaces = SurfaceCollection(
            config=[
                ConfigSurface(
                    name="DATABASE_URL",
                    env_var_name="DATABASE_URL",
                    enrichment={
                        "inferred_intent": "Postgres connection string",
                    },
                )
            ]
        )
        text = generate_env_example(surfaces, tmp_path).read_text()
        assert "Postgres connection string" in text
